FROM denoland/deno:debian-2.9.1

ENV PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright

# Install Playwright Chromium and its dependencies
RUN deno run -A npm:playwright@1.61.0 install --with-deps chromium
